### ISSUE TITLE
Pin connections to RPi

### ISSUE THREAD

**Issue by anildadj** [mgrau/ad9959#1]
Hi,
Thats a great piece of work. 
I want to use the AD9959.py class file for using the board for single-tone mode generation. I just have one question: To which pins in AD9959 are the GPIO pins 15, 13, 11, 12 are connected? You mention them as _CHPINS in the code.
I have an evaluation board which only has a serial communication port with pins SD0, SD1, SD2, SD3; RESET, IO_UP, CS, SCK,  P0, P1, P2, P3, GND.

**Comment by mgrau** [comment]
Those are attached to the profile pins P0, P1, P2, and P3.

**Comment by rprr** [comment]
Many thanks for this repo. 

I have a similar board but struggling to get it working with the Raspberry Pi 3B+. The board has an internal 25 MHz reference. I am trying to get the command line AD9959.py working. Your code only mentions the 6 pins. Besides these six, I assume I also need to hookup SD0, SD2, CS, SCK, GND on my board to MOSI, MISO, CE0, SCLK, GND on the RPi. I also pulled SD3 to ground. Do I need to make any other connections or modifications since I'm not using the RPi clock? Thanks for your help.

**Comment by mgrau** [comment]
That hookup looks correct. You shouldn't need any other modification other than changing the clock frequency to match your provided reference of 25 MHz. Remember that you will need to apply power to the DAC analog channels as well as the DDS 3.3V and 1.8V. Also if you want to perform read back you will first need to send the command to put the DDS in 2 wire mode.

**Comment by rprr** [comment]
Thanks. I'm just not able to get it to work. :(

> import AD9959
> dds=AD9959.AD9959()
> Refclock = 5.00e+07 Hz 
> Freqmult = 10 
> Clock Frequency = 5.00e+08 Hz
> dds.set_refclock(25e6)
> Refclock = 2.50e+07 Hz 
> Freqmult = 10 
> Clock Frequency = 2.50e+08 Hz
> dds.frequencies
> [0, 0, 0, 0]
> dds.set_output(0,99.5e6,'frequency',io_update=True)
> dds.set_output(0,1,'amplitude',io_update=True)
> dds.frequencies
> [99500000, 0, 0, 0]
> dds.amplitudes
> [1, 1, 1, 1]

There is no output. :(

Question: What is the command to put the SPI into two wire mode?

**Comment by rprr** [comment]
Ok, there seems to be an output at 100 MHz. Now I cannot seem to reset it :( Somehow cannot get channel active again.

dds.get_activechannels() returns nothing. Very puzzled. 

Also dds.get_state() returns all zeros.

**Comment by rprr** [comment]
Still no luck. Maybe my board became damaged, The board outputs a 100 MHz tone. I cannot seem to change anything anymore.

**Comment by ivanprostran** [comment]
Hi,
Have you managed to start the board?
I am pretty desperate about it.


> , I assume I also need to hookup SD0, SD2, CS, SCK, GND on my board to MOSI, MISO, CE0, SCLK, GND on the RPi. I also pulled SD3 to ground

This confuses me a bit.
How can it be possible to use the following mapping:

### SPI MAPPING

```
MOSI --> SD0
MISO --> SD2
CE0  --> CS
SCK  --> SCLK
GND  --> GND 
GND  --> SD03
```
Combined with NON-SPI scheme/mapping (mgrau wrote: Those are attached to the profile pins P0, P1, P2, and P3.)

### NON-SPI MAPPING

```
15  --> P0
13  --> P1 
11  --> P2
12  --> P3
```

When, at least on my device ( Pi Model 2B  V1.1 ) , **GPIO11 is actually   SPI_CLK**

so this is mutually exclusive:

```
Mapping SPI:        SCK  --> SCLK
Mapping NON-SPI:     11  --> P2
```

Thank you fro your time.
Regards,
Ivan

**Comment by ivanprostran** [comment]
Additional comment:

I remapped 15,13,11,12 to different GPIO pins: gpio 22, 27,18, 17

Please notice I have old RPI (Pi Model 2B V1.1)


And of course RTFM:

**gpio.setmode(gpio.BOARD)**

gpio.setup(IOUPDATE_PIN, gpio.OUT)
gpio.setup(RESET_PIN, gpio.OUT)
gpio.setup(PIN_0, gpio.OUT)
gpio.setup(PIN_1, gpio.OUT)
gpio.setup(PIN_2, gpio.OUT)
gpio.setup(PIN_3, gpio.OUT)

That is clear now :)
